name: Playwright Tests
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  ui-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright UI tests
        run: npx playwright test --project="UI Tests" # Specify UI Tests project
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      API_TOKEN: ${{ secrets.API_TOKEN }} # Access the secret API_TOKEN here for API tests only
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright API tests
        run: npx playwright test --project="API Tests" # Specify API Tests project
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}  # Only upload if not canceled
        with:
          name: playwright-report
          path: playwright-report/  # Path to the generated Playwright report
          retention-days: 30